name: pr
on:
  pull_request:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: main
          error-on-no-successful-workflow: true
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Check formatting
        run: npx nx format:check --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      - name: Lint affected
        run: npx nx affected --target=lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      - name: Build affected
        run: npx nx affected --target=build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      - name: Test affected
        run: npx nx affected --target=test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
