name: pr
on:
  pull_request:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: main
          error-on-no-successful-workflow: true
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: '16'
      - run: npm ci
      - run: npx nx format:check --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      - run: npx nx affected --target=lint --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      - run: npx nx affected --target=build --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
      - run: npx nx affected --target=test --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
